spring:
  datasource:
    url: jdbc:mysql://13.125.37.153:3306/capston?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: 13.125.37.153
      port: 6379
      password: root
      cache:
        expiration-after-write-policy: 1h
    session:
      store-type: redis
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.hibernate.SQL: debug
server:
  shutdown: graceful


